### PR TITLE
Created new note UI and fixed form validation

### LINKED ISSUE #5: Create new note UI

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #5 

Made changes according to the reviews.

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/DeleteAlert.jsx [hunk 1]
```diff
@@ -2,11 +2,11 @@ import React from "react";
 
 import { Alert } from "neetoui";
 
-const DeleteAlert = ({ onClose, selectedNote, handleDelete }) => (
+const DeleteAlert = ({ onClose, handleDelete, selectedNote }) => (
   <Alert
     isOpen
-    message="Are you sure you want to continue? This cannot be undone."
-    title={`Delete ${selectedNote.title}`}
+    message={`Are you sure you want to delete the ${selectedNote} ? This action cannot be undone.`}
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/DeleteAlert.jsx:8]:
```suggestion
    message={`Are you sure you want to delete the note, "${selectedNote}"? This action cannot be undone.`}
```

File: app/javascript/src/components/Dashboard/Notes/Pane/CreateNotePane.jsx [hunk 2]
```diff
@@ -6,7 +6,7 @@ import Form from "./Form";
 
 import { NOTES_FORM_INITIAL_FORM_VALUES } from "../constants";
 
-const NewNotePane = ({ showPane, setShowPane }) => {
+const CreateNotePane = ({ showPane, setShowPane }) => {
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Pane/CreateNotePane.jsx:9]: https://academy.bigbinary.com/learn-react/pages/structuring-code#:~:text=Avoid%20Unnecessary%20Namespacing

File: app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx [hunk 3]
```diff
@@ -46,7 +46,28 @@ const NoteForm = ({ onClose, note, isEdit }) => {
...
+            <Select
+              isClearable
+              isMulti
+              isSearchable
+              required
+              className="w-full flex-grow-0"
+              label="Tags"
+              name="tags"
+              options={TAGS}
+              placeholder="Select tag"
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Pane/Form.jsx:70]:
```suggestion
              placeholder="Select tags"
```

File: app/javascript/src/components/Dashboard/Notes/constants.js [hunk 4]
```diff
@@ -3,41 +3,103 @@ import * as yup from "yup";
...
+  },
+  {
+    label: "Bugs",
+    value: "Bugs",
+  },
+  {
+    label: "V2",
+    value: "V2",
+  },
+];
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/constants.js:83]: Build these select options rather than hardcoding.

**Review by yedhink — CHANGES_REQUESTED** [review]
@gaagul

File: app/javascript/src/components/Dashboard/Notes/constants.js (hunk 4 above)
Comment (gaagul) [reply app/javascript/src/components/Dashboard/Notes/constants.js:83]: I did not understand what you meant by building the select options,
I made this constant since this is the format the Select component accepts in the options attribute,
I am not able to find out what I am doing wrong here, can you please point it out to me?

Comment (yedhink) [reply app/javascript/src/components/Dashboard/Notes/constants.js:83]: @gaagul https://bigbinary.slack.com/archives/C01T5Q4DZAR/p1663335627615309?thread_ts=1663060378.971029&cid=C01T5Q4DZAR

Comment (gaagul) [reply app/javascript/src/components/Dashboard/Notes/constants.js:83]: Thank you for pointing it out to me.
I will make sure that necessary changes will be made to the code and I will keep this in mind for the future also.
